ALTER TABLE schools
  ADD COLUMN IF NOT EXISTS minimum_app_version VARCHAR(20) NOT NULL DEFAULT '1.0.0',
  ADD COLUMN IF NOT EXISTS force_update_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS payment_banner_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS payment_banner_reason VARCHAR(280) NULL;
