/**
 * Celebration Event Engine domain constants.
 * V1 activates BIRTHDAY only. Remaining types are reserved extension points.
 */

export const CELEBRATION_EVENT_TYPES = Object.freeze({
  BIRTHDAY: 'BIRTHDAY',
  WORK_ANNIVERSARY: 'WORK_ANNIVERSARY',
  STUDENT_ACHIEVEMENT: 'STUDENT_ACHIEVEMENT',
  EXAM_TOPPER: 'EXAM_TOPPER',
  SPORTS_WINNER: 'SPORTS_WINNER',
  TEACHER_APPRECIATION: 'TEACHER_APPRECIATION',
  SCHOOL_ANNIVERSARY: 'SCHOOL_ANNIVERSARY',
  FESTIVAL: 'FESTIVAL',
});

export const CELEBRATION_TARGET_TYPES = Object.freeze({
  STUDENT: 'STUDENT',
  STAFF: 'STAFF',
});

export const CELEBRATION_SLIDE_TYPE = 'CELEBRATION';

export const CELEBRATION_PRIORITIES = Object.freeze({
  EMERGENCY: 100,
  CRITICAL_NOTICE: 90,
  IMPORTANT_NOTICE: 80,
  BIRTHDAY: 70,
  SCHOOL_EVENT: 60,
  NORMAL_BANNER: 50,
  PROMOTION: 20,
});
